name: CICD

on:
  push:
    branches:
      - main
    paths:
      - 'videoML/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'videoML/**' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ./videoML/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./videoML/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: ./videoML 
        
      - name: Build project
        run: npm run prepare:package
        working-directory: ./videoML  
        
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./videoML/dist